refactor: flatten constraint layout
lude-dev/niche-android pull request #43
Opened 2021-06-07 14:50 UTC by Gijuno

in fragment_home_slide.xml

2021-06-07 14:56 UTC, nutyworks requested changes

2021-06-07 14:56 UTC, nutyworks commented on app/src/main/res/layout/fragment_home_slide.xml
>          </LinearLayout>
LinearLayout can be flattened with `app:layout_constraintVertical_bias` property.

2021-06-07 14:58 UTC, Gijuno commented on app/src/main/res/layout/fragment_home_slide.xml
>          </LinearLayout>
You mean refactor 119 .. 122 line to layout_constraintVertical_bias?

2021-06-07 15:00 UTC, nutyworks commented on app/src/main/res/layout/fragment_home_slide.xml
>          </LinearLayout>
You can remove LinearLayout and use `app:layout_constraintVertical_bias` property on TextViews.

2021-06-07 16:04 UTC, nutyworks requested changes

2021-06-07 16:04 UTC, nutyworks commented on app/src/main/res/layout/fragment_home_slide.xml
> +            app:layout_constraintVertical_bias="0" />
Please constraint TextViews to icons, not the parent.

2021-06-08 03:40 UTC, nutyworks approved these changes
LGTM 👍

2021-06-08 05:24 UTC, merged