feat: add user tab layout elements
lude-dev/niche-android pull request #59
Opened 2021-06-12 03:22 UTC by Gijuno

2021-06-12 06:37 UTC, nutyworks requested changes

2021-06-12 06:37 UTC, nutyworks commented on app/src/main/res/values/colors.xml
> +    <color name="aqua_marin">#2CADC0</color>
aquamarine

2021-06-13 05:57 UTC, Gijuno commented on app/src/main/res/values/colors.xml
> +    <color name="aqua_marin">#2CADC0</color>
lolll

2021-06-13 06:17 UTC, nutyworks approved these changes

2021-06-13 06:18 UTC, merged